// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/ItWorks.tsx";
import * as $$$$$$1 from "./sections/Theme/Theme.tsx";

const manifest = {
  "sections": {
    "deco-sites/guispositostudy/sections/ItWorks.tsx": $$$$$$0,
    "deco-sites/guispositostudy/sections/Theme/Theme.tsx": $$$$$$1,
  },
  "apps": {
    "deco-sites/guispositostudy/apps/decohub.ts": $$$$$$$$$$$0,
    "deco-sites/guispositostudy/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "deco-sites/guispositostudy",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
